#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2018.2.7f1_4ebd28dd9664"
#define UNITY_VERSION_FULL_NICE "2018.2.7f1 (4ebd28dd9664)"
#define UNITY_VERSION_BLD 5160232
#define UNITY_VERSION_DATE 1535633740
#define UNITY_VERSION_WIN "2018.2.7.5160232"
#define UNITY_VERSION_BRANCH "2018.2/release"
